# fly.toml app configuration file generated for staging-pupcle on 2023-05-24T19:14:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "staging-pupcle"
primary_region = "nrt"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "production.Dockerfile"

[build.args]
  ROOT_URL = "https://staging-pupcle.fly.dev"
  TARGET = "server"

[env]
  NODE_ENV = "production"
  DATABASE_AUTHENTICATOR = "staging_pupcle_authenticator"
  DATABASE_VISITOR = "staging_pupcle_visitor"
  ROOT_URL = "https://staging-pupcle.fly.dev"
  GRAPHILE_TURBO = "1"
  FROM_EMAIL_DOMAIN = "staging-pupcle.com"
  AWS_BUCKET_UPLOAD = "staging-pupcle-upload"
  S3_HOST = "staging-pupcle-upload.s3-website-us-west-2.amazonaws.com"
  S3_ACCESS_KEY_ID = "AKIAXP474PBJEOOMJUPA"
  AWS_ACCESS_KEY_ID = "AKIAXP474PBJEOOMJUPA"

[deploy]
  release_command = "yarn db migrate"
