app = "prod-pupcle"
primary_region = "nrt"

[processes]
  server = "yarn server start"
  worker = "yarn worker start"

[http_service]
  processes = ["server"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[build]
  dockerfile = "production.Dockerfile"

[build.args]
  NODE_ENV = "production"
  PORT = "8080"
  ROOT_URL = "https://pupcle.com"
  TARGET = "server"

[env]
  NODE_ENV = "production"
  DATABASE_AUTHENTICATOR = "pupcle_authenticator"
  DATABASE_VISITOR = "pupcle_visitor"
  ROOT_URL = "https://pupcle.com"
  GRAPHILE_TURBO = "1"
  FROM_EMAIL_DOMAIN = "pupcle.com"
  AWS_BUCKET_UPLOAD = "staging-pupcle-upload"
  S3_HOST = "s3.us-west-2.amazonaws.com"
  S3_ACCESS_KEY_ID = "AKIAXP474PBJEOOMJUPA"
  AWS_ACCESS_KEY_ID = "AKIAXP474PBJEOOMJUPA"
  SMTP_HOST = "in-v3.mailjet.com"
  SMTP_PORT = "587"
  SMTP_USERNAME = "2148035174c244d1b7dd80e1c4488d1a"
  DISCOURSE_URL = "https://circle.pupcle.com"

[deploy]
  release_command = "yarn db migrate"
