drop trigger if exists _100_timestamps on app_public.poi_favorites;
drop trigger if exists _100_timestamps on app_public.poi_reviews;
drop trigger if exists _200_poi_reviews_create_poi on app_public.poi_reviews;
drop function if exists app_public.tg__poi_reviews__create_poi();
drop trigger if exists _300_poi_reviews_check_kakao_id on app_public.poi_reviews;
drop function if exists app_public.tg__poi_reviews__check_kakao_id();
drop trigger if exists _400_poi_reviews_after_change on app_public.poi_reviews;
drop function if exists app_public.tg__poi_reviews__update_poi_on_review();
drop trigger if exists _100_timestamps on app_public.poi;
drop table if exists app_public.poi_favorites;
drop table if exists app_public.poi_reviews;
drop table if exists app_public.poi;
